### ISSUE TITLE
socketio errors on go get

### ISSUE THREAD

**Issue by Dieterbe** [spf13/kaiju#6]
```
dieter@dieter-m6800 ~  go get github.com/spf13/kaiju
# github.com/spf13/kaiju/commands
go/src/github.com/spf13/kaiju/commands/sio.go:32: undefined: socketio.SocketIOServer
go/src/github.com/spf13/kaiju/commands/sio.go:35: undefined: socketio.Config
go/src/github.com/spf13/kaiju/commands/sio.go:39: undefined: socketio.NewSocketIOServer
go/src/github.com/spf13/kaiju/commands/sio.go:72: undefined: socketio.NameSpace
go/src/github.com/spf13/kaiju/commands/sio.go:79: undefined: socketio.NameSpace
go/src/github.com/spf13/kaiju/commands/sio.go:86: undefined: socketio.NameSpace
go/src/github.com/spf13/kaiju/commands/sio.go:100: undefined: socketio.NameSpace
go/src/github.com/spf13/kaiju/commands/sio.go:133: undefined: socketio.NameSpace

```

**Comment by thomasmodeneis** [comment]
duplicated of #2

**Comment by Dieterbe** [comment]
whoopsie

**Comment by thomasmodeneis** [comment]
This is work in progress to have it fixed. 
We will be releasing a new version of kaiju pairing with the latest socket.io implementations.

**Comment by Dieterbe** [comment]
cool looking forward to play with kaiju.
@thomasmodeneis do you use it "for real" ?

**Comment by thomasmodeneis** [comment]
Hi Dieter,
As an opensource tool, Kaiju is not the only one.

I've been doing some work on the project but I've been quite busy with
other tasks and I had to stop the prototype.
I will be releasing something soon that may bring Kaiju back to the game,
it worth waiting if you still want to use Golang as base for comments
solution.

If you have a more urgent problem that need imediate attention, there are
other solutions you can check.
The only one you would be able to self host is isso, others are cloud
solutions and you wont be owning your own data (may be good for one side,
but some people want to manage their own data), and well I'm no Py dev so I
can't say anything more.
- IntenseDebate http://intensedebate.com/
- Livefyre http://livefyre.com/
- Muut http://muut.com/
- 多说 http://duoshuo.com/ (Duoshuo http://duoshuo.com/, popular in
  China)
- isso http://posativ.org/isso/ (Self-hosted, Python)
